AbduqayumovBlog/Controllers/AuthenController.cs
using BlogWithDb.Models;
using DataAccess.Entities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
//using Microsoft.VisualBasic;
//using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace BlogWithDb.Controllers
{
    public class AuthenController : Controller
    {
        public AuthenController()
        {

        }
        public IActionResult Login()
        {
            ClaimsPrincipal claimUser = HttpContext.User;

            if (claimUser.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");


            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            if (loginModel.Username == "Admin" && loginModel.Password == "123")
            {
                List<Claim> claims = new List<Claim>()
                {
                    new Claim(ClaimTypes.NameIdentifier, loginModel.Username)
                };

                ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims,
                    CookieAuthenticationDefaults.AuthenticationScheme);

                AuthenticationProperties properties = new AuthenticationProperties()
                {
                    AllowRefresh = true,
                    IsPersistent = false,

                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity), properties);
                return RedirectToAction("Index", "Home");
            }
            ViewData["ValidateMessage"] = "User not found!";
            return View();
        }
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

    }

}

AbduqayumovBlog/Views/Authen/Index.cshtml
@model BlogWithDb.Models.LoginModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .blue-container {
        color: #fff;
        background: #3598dc;
        font-family: 'Roboto', sans-serif;
    }

    .form-control {
        height: 41px;
        background: #f2f2f2;
        box-shadow: none !important;
        border: none;
    }

        .form-control:focus {
            background: #e2e2e2;
        }

    .form-control, .btn {
        border-radius: 3px;
    }

    .signup-form {
        width: 400px;
        margin: 0px auto;
        height: calc(100vh - 120px);
    }

        .signup-form form {
            color: #999;
            border-radius: 3px;
            margin-bottom: 15px;
            background: #fff;
            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            padding: 30px;
        }

        .signup-form h2 {
            color: #333;
            font-weight: bold;
            margin-top: 0;
        }

        .signup-form hr {
            margin: 0 -30px 20px;
        }

        .signup-form .form-group {
            margin-bottom: 20px;
        }

        .signup-form input[type="checkbox"] {
            margin-top: 3px;
        }

        .signup-form .row div:first-child {
            padding-right: 10px;
        }

        .signup-form .row div:last-child {
            padding-left: 10px;
        }

        .signup-form .btn {
            font-size: 16px;
            font-weight: bold;
            background: #3598dc;
            border: none;
            min-width: 140px;
        }

            .signup-form .btn:hover, .signup-form .btn:focus {
                background: #2389cd !important;
                outline: none;
            }

        .signup-form a {
            color: #fff;
            text-decoration: underline;
        }

            .signup-form a:hover {
                text-decoration: none;
            }

        .signup-form form a {
            color: #3598dc;
            text-decoration: none;
        }

            .signup-form form a:hover {
                text-decoration: underline;
            }

        .signup-form .hint-text {
            padding-bottom: 15px;
            text-align: center;
        }
</style>
<div class="blue-container">
    <div class="signup-form pt-5">
        @using (@Html.BeginForm("Login", "Authen", FormMethod.Post))
        {
            <h2>Login</h2>
            <p>Enter your email and password to login</p>
            <hr>
            <div class="form-group">
                @Html.TextBoxFor(m => m.Username, new { @class = "form-control", type = "email", placeholder = "Email", required = "required" })
            </div>
            <div class="form-group">
                @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password", required = "required" })
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg">Login</button>
            </div>
        }
        <div class="hint-text">Need an account? <a href="#">Sign up here</a></div>
    </div>
</div>

AbduqayumovBlog/Views/Authen/Login.cshtml
@model BlogWithDb.Models.LoginModel;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .blue-container {
        color: #fff;
        background: #3598dc;
        font-family: 'Roboto', sans-serif;
    }

    .form-control {
        height: 41px;
        background: #f2f2f2;
        box-shadow: none !important;
        border: none;
    }

        .form-control:focus {
            background: #e2e2e2;
        }

    .form-control, .btn {
        border-radius: 3px;
    }

    .signup-form {
        width: 400px;
        margin: 0px auto;
        height: calc(100vh - 120px);
    }

        .signup-form form {
            color: #999;
            border-radius: 3px;
            margin-bottom: 15px;
            background: #fff;
            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            padding: 30px;
        }

        .signup-form h2 {
            color: #333;
            font-weight: bold;
            margin-top: 0;
        }

        .signup-form hr {
            margin: 0 -30px 20px;
        }

        .signup-form .form-group {
            margin-bottom: 20px;
        }

        .signup-form input[type="checkbox"] {
            margin-top: 3px;
        }

        .signup-form .row div:first-child {
            padding-right: 10px;
        }

        .signup-form .row div:last-child {
            padding-left: 10px;
        }

        .signup-form .btn {
            font-size: 16px;
            font-weight: bold;
            background: #3598dc;
            border: none;
            min-width: 140px;
        }

            .signup-form .btn:hover, .signup-form .btn:focus {
                background: #2389cd !important;
                outline: none;
            }

        .signup-form a {
            color: #fff;
            text-decoration: underline;
        }

            .signup-form a:hover {
                text-decoration: none;
            }

        .signup-form form a {
            color: #3598dc;
            text-decoration: none;
        }

            .signup-form form a:hover {
                text-decoration: underline;
            }

        .signup-form .hint-text {
            padding-bottom: 15px;
            text-align: center;
        }
</style>
<div class="blue-container">
    <div class="signup-form pt-5">
        <form asp-action="Login" asp-controller="Authen" method="post">
            <h2>Login</h2>
            <p>Enter your email and password to login</p>
            <hr>
            <div class="form-group">
                @Html.TextBoxFor(m => m.Username, new { @class = "form-control", type = "Username", placeholder = "Username", required = "required" })
            </div>
            <div class="form-group">
                @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password", required = "required" })
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg">Login</button>
            </div>
        </form>
        <div class="hint-text">@if(ViewData["ValidateMessage"] != null)
        {
            <label>@ViewData["ValidateMessage"]</label>
        }</div>
    </div>
</div>

AbduqayumovBlog/Views/Authen/Register.cshtml
@model BlogWithDb.Models.RegisterModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Create User</h2>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register" asp-controller="Authen">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username"/>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password"/>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email"/>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>