AbduqayumovBlog/Controllers/BlogController.cs
using BlogWithDb.Models;
using BlogWithDb.Services;
using DataAccess;
using DataAccess.Entities;
using DataAccess.Repositorys;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SelectPdf;

namespace BlogWithDb.Controllers
{
    public class BlogController : Controller
    {
        private readonly IGenericCRUDService<PostResponseModel, PostRegisterModel> _postSvc;
        private readonly ICommentCRUDService<CommentResponseModel, CommentRegisterModel> _commentSvc;
        public BlogController(IGenericCRUDService<PostResponseModel, PostRegisterModel> postSvc, ICommentCRUDService<CommentResponseModel, CommentRegisterModel> commentSvc)
        {
            _postSvc = postSvc;
            _commentSvc = commentSvc;
        }

        [HttpGet]
        
        public async Task<IActionResult> Index()
        {
            var result = await _postSvc.Get();
            return View(result);
        }
        public async Task<IActionResult> Read(int id)
        {
            var post = await _postSvc.Get(id);
            var comments = await _commentSvc.Get(id);
            var data = new ReadViewModel()
            {
                Comments = comments.ToList(),
                Posts = post
            };
            return View("Read", data);
        }
        [HttpPost]
        public async Task<IActionResult> Read(ReadViewModel model)
        {
            model.CommentRegister.PostId = model.Posts.Id;
            await _commentSvc.Create(model.CommentRegister);
            return RedirectToAction();
        }
        public IActionResult Post()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Post(PostRegisterModel post)
        {
            if (!ModelState.IsValid)
                return View();
            await _postSvc.Create(post);

            return View();
        }
        public async Task<IActionResult> Edit(int id)
        {
            var post = await _postSvc.Get(id);
            return View(post);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, PostResponseModel post)
        {
            await _postSvc.Update(id, post);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _postSvc.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult UploadImage(List<IFormFile> files)
        {
            var filepath = "";
            foreach(IFormFile photo in Request.Form.Files)
            {
                string serverMapPath = Path.Combine("Image", photo.FileName);
                using (var stream = new FileStream(serverMapPath, FileMode.Create))
                {
                    photo.CopyTo(stream);
                }
                filepath = "https://localhost://251" + "Image/" + photo.FileName;
            }
            return Json(new {url = filepath});
        }

    }
}

AbduqayumovBlog/Controllers/ContactController.cs
using BlogWithDb.Models;
using Microsoft.AspNetCore.Mvc;

namespace BlogWithDb.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(TelegramMessageModel telegramMessageModel)
        {
            if(telegramMessageModel == null)
                return View();
            string message = $"✅ Sender: {telegramMessageModel.Name}. \nTelegram: {telegramMessageModel.Telegram}. \nSubject: {telegramMessageModel.Subject}. \nMessage: {telegramMessageModel.Message}";
            var uri = new Uri($"https://api.telegram.org/bot5956336067:AAEL8mQkrTEJL2ll5L59CSXao7NFBL1CYpw/sendmessage?text={message}&chat_id=859694843");
            HttpClient client = new HttpClient();
            var response = await client.PostAsync(uri, null);

            return View("Back");
        }
        public string Back()
        {
            return "salom";
        }
    }
}

AbduqayumovBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Abbosjon's Blog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/MyCostum.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogWithDb.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet"> 

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/front/animate/animate.min.css" rel="stylesheet">
    <link href="lib/front/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="lib/front/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    @*<!-- Customized Bootstrap Stylesheet -->
    <link href="~/lib/front/css/bootstrap.min.css" rel="stylesheet">
*@
    <!-- Template Stylesheet -->
    <link href="/lib/front/css/style.css" rel="stylesheet">

</head>
<body>


    @*<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
*@

    <header class="sticky-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="text-center container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Abbosjon's Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" target="_blank" href="https://t.me/Abduqayumov">Channel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Abduqayumov.uz
        </div>
    </footer>
        @*<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>*@


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>




    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    @*<script src="lib/front/wow/wow.min.js"></script>*@
    <script src="lib/front/easing/easing.min.js"></script>
    <script src="lib/front/waypoints/waypoints.min.js"></script>
    <script src="lib/front/typed/typed.min.js"></script>
    <script src="lib/front/counterup/counterup.min.js"></script>
    <script src="lib/front/owlcarousel/owl.carousel.min.js"></script>
    <script src="lib/front/isotope/isotope.pkgd.min.js"></script>
    <script src="lib/front/lightbox/js/lightbox.min.js"></script>


    <script src="lib/front/main.js"></script>



    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>