AbduqayumovBlog/Controllers/AboutMeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogWithDb.Controllers
{
    public class AboutMeController : Controller
    {   
        public IActionResult Index()
        {
            return View();
        }
    }
}

AbduqayumovBlog/Controllers/BlogController.cs
using BlogWithDb.Models;
using BlogWithDb.Services;
using DataAccess;
using DataAccess.Entities;
using DataAccess.Repositorys;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SelectPdf;

namespace BlogWithDb.Controllers
{
    public class BlogController : Controller
    {
        private readonly IGenericCRUDService<PostResponseModel, PostRegisterModel> _postSvc;
        private readonly ICommentCRUDService<CommentResponseModel, CommentRegisterModel> _commentSvc;
        public BlogController(IGenericCRUDService<PostResponseModel, PostRegisterModel> postSvc, ICommentCRUDService<CommentResponseModel, CommentRegisterModel> commentSvc)
        {
            _postSvc = postSvc;
            _commentSvc = commentSvc;
        }

        [HttpGet]
        
        public async Task<IActionResult> Index()
        {
            var result = await _postSvc.Get();
            return View(result);
        }
        public async Task<IActionResult> Read(int id)
        {
            var post = await _postSvc.Get(id);
            var comments = await _commentSvc.Get(id);
            var data = new ReadViewModel()
            {
                Comments = comments.ToList(),
                Posts = post
            };
            return View("Read", data);
        }
        [HttpPost]
        public async Task<IActionResult> Read(ReadViewModel model)
        {
            model.CommentRegister.PostId = model.Posts.Id;
            await _commentSvc.Create(model.CommentRegister);
            return RedirectToAction();
        }
        public IActionResult Post()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Post(PostRegisterModel post)
        {
            if (!ModelState.IsValid)
                return View();
            await _postSvc.Create(post);

            return View();
        }
        public async Task<IActionResult> Edit(int id)
        {
            var post = await _postSvc.Get(id);
            return View(post);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, PostResponseModel post)
        {
            await _postSvc.Update(id, post);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _postSvc.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult UploadImage(List<IFormFile> files)
        {
            var filepath = "";
            foreach(IFormFile photo in Request.Form.Files)
            {
                string serverMapPath = Path.Combine("Image", photo.FileName);
                using (var stream = new FileStream(serverMapPath, FileMode.Create))
                {
                    photo.CopyTo(stream);
                }
                filepath = "https://localhost://251" + "Image/" + photo.FileName;
            }
            return Json(new {url = filepath});
        }

    }
}

AbduqayumovBlog/Controllers/HomeController.cs
using BlogWithDb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogWithDb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult NoAccess()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AbduqayumovBlog/Views/Home/Index.cshtml
<div class="container-fluid" id="home">
        <div class="container">
            <br /><br /><br /><br />
            <div class="row g-5 align-items-center">
                <div class="col-lg-3">
                    <img class="rounded-circle" width="280" height="280" src="img/Abbos.png" alt="">
                </div>
                <div class="col-lg-6 py-2 pb-0">
                    <h3 class="text-primary mb-3">I'm</h3>
                    <h1 class="display-5 mb-3">Abbos Abduqayumov</h1>
                    <p class="text-muted">Hi there. I'm .NET developer. I write about technical and non-technical.</p>
                    <div class="d-flex align-items-center pt-5">
                        <a class="btn btn-outline-info py-3 px-4 me-5" asp-controller="Blog" asp-action="Index">Read Blog</a>
                        <a asp-controller="AboutMe" asp-action="index" class="btn btn-outline-info py-3 px-4 me-5">About me</a>
                    </div>

                </div>

            </div>
        </div>
    </div>

AbduqayumovBlog/Views/Home/NoAccess.cshtml
@{
    ViewData["Title"] = "No Access";
}

<h3>You don't have access!</h3>